backend:
  name: github
  repo: yangreform/developers.github.io
  branch: main

publish_mode: simple

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "properties"
    label: "房產清單"
    folder: "_properties"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "地點", name: "location", widget: "string" }
      - { label: "價格", name: "price", widget: "string" }
      - { label: "主圖", name: "image", widget: "image" }
      - { label: "描述", name: "description", widget: "text" }
